### ISSUE TITLE
Wrong plugin name submitted when uploading a plugin config

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-admin-ui#165]
Plugins configurations can be uploaded to `/1.0/kb/tenants/uploadPluginConfig/XXX` where `XXX` is the plugin name (`killbill-paypal-express`, `killbill-braintree_blue`, `killbill-stripe`, etc.).

This can be done via the `admin_tenants` page (`active_tab=PluginConfig`). While the plugin name text field matches the KPM key (i.e. the `pluginKey`, see http://docs.killbill.io/latest/plugin_management.html), the code should map it to a plugin name before uploading the config to Kill Bill: https://github.com/killbill/killbill-admin-ui/blob/db23a54f6033a0fda8a3e6a44f8a8a82dc4a4720/app/controllers/kaui/admin_tenants_controller.rb#L306

According to [this thread](https://groups.google.com/forum/#!msg/killbilling-users/t3nSoMYsms4/k5CTj-MOCAAJ), this doesn't seem to always be the case.

We should:

* Investigate what happened in the case reported on the mailing-list
* Make the process more robust. Some ideas:
  * When the user enters a plugin key (e.g. `paypal`), we should check  (via an AJAX call) the nodes info API to see if there is a matching plugin installed on the server. If not, don't prevent the upload but display a warning message to the user by the form.
  * Provide a _did you mean?..._ hint: if the user enters `killbill-paypal` or `paypal-express`, have an info message by the form which says "Official plugin not found, did you mean 'paypal'?" (such fuzzy matches can be quite tricky but we don't have to go too crazy...)

**Comment by Mykola-Morozov** [comment]
Prerequisites
* You should have set up docker images for killbill_db, killbill/0.18.19, kaui/0.9.0
* You should have included killbill-paypal-express-plugin/5.0.7 in your killbill application

Steps to reproduce
1. Create a tenant
2. Go to a Plugin configuration tab for the tenant
3. Start typing "paypal". Kaui will help you with options and fields "Signature, Login, Password" will appear
![killbill-paypal-config](https://user-images.githubusercontent.com/38116488/38392272-9e759022-392f-11e8-971f-7c9fc56ecc62.png)
4. Fill in plugin data and press "Upload" button
5. Next time you navigate to this configuration tab and type "paypal" you will see your already uploaded data.

**Issue is**: this plugin configuration doesn't work.
From DB perpective created row in tenant_kvs table has **tenant_key=PLUGIN_CONFIG_killbill-paypal**.

**Comment by pierre** [comment]
Work left:

* De-duplicate `Installed` plugins list in the drop down: it's possible to have multiple instances of the PayPal plugin installed for instance (even though only one is active at any given time)
* In `get_tenant_plugin_config`, it is assumed that Ruby configs are YAML and Java configs are key=value pairs. This historically used to be the case, but isn't anymore. Newer Java plugins now use YAML for instance (see https://github.com/killbill/killbill-bridge-plugin/tree/work-for-release-0.19.x#configuration for an example). The implementation shouldn't make these assumptions anymore.
* The sort function for the drop down is incorrect. I think it needs to sort separately the two sections (installed and non-installed). Take a look at `[{:plugin_key=>"payment_bridge", :plugin_name=>"killbill-bridge", :plugin_type=>:java, :installed=>true}, {:plugin_key=>"zendesk", :plugin_name=>"killbill-zendesk", :plugin_type=>:ruby, :installed=>false}, {:plugin_key=>"stripe", :plugin_name=>"killbill-stripe", :plugin_type=>:ruby, :installed=>false}, {:plugin_key=>"payment-test", :plugin_name=>"killbill-payment-test", :plugin_type=>:ruby, :installed=>false}, {:plugin_key=>"adyen", :plugin_name=>"killbill-adyen", :plugin_type=>:java, :installed=>false}]` for an example.
* The select dropdown doesn't seem to work for me on `Chrome Version 66.0.3359.181 (Official Build) (64-bit)`. When I click `select_plugin_name` to select my plugin (when opening the dropdown), the handler is invoked with `e.target.localName == select`. After I click on the plugin though, the handler isn't invoked again.
* The AJAX call to `suggest_plugin_name` can be quite slow, it would be nice to show a spinner next to the text field to show the user something is happening. Also, suggestions and plugin config forms should be cleared before making the call (otherwise, it can be confusing as old entries are shown while making the suggested call).
* It looks like there are some `console.log` leftovers.

**Comment by pierre** [comment]
All items fixed. See https://github.com/killbill/killbill-admin-ui/issues/203 for a follow-up.
