### ISSUE TITLE
Review DataTables integration

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-admin-ui#175]
We rely on the `jquery-datatables-rails` gem to integrate DataTables in Kaui and various plugins, but the gem doesn't seem maintained (last update in 2016).

We should find a more recent gem and/or integrate DataTables directly instead, so we can use the latest features. See https://github.com/killbill/killbill-analytics-ui/pull/19#discussion_r180829388.

Do a pass at updating all mountable engines.

**Comment by tungleduyxyz** [comment]
We did not use the jquery-datatables-rails gem anymore.
Datatable is now handled by killbill-assest-ui, and we're using the raw JS and CSS files directly.
cc: @pierre
