### ISSUE TITLE
Display UUIDs in a more user-friendly way, pass 2

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-admin-ui#209]
See comments here: https://github.com/killbill/killbill-admin-ui/pull/201#issuecomment-394400090.

**Comment by pierre** [comment]
Work left: `copy-icon` doesn't seem to have any effect on Chrome (https://github.com/killbill/killbill-admin-ui/pull/211#issuecomment-397046548).

**Comment by kpbacode** [comment]
1. `copy-icon` is working for audit tab
![Screenshot 2022-09-27 at 12 31 13](https://user-images.githubusercontent.com/65641209/192503046-e8be3123-6af5-4fa9-b9e4-213c1ec2041b.png)

**Comment by kpbacode** [comment]
![Screenshot 2022-09-27 at 12 40 43](https://user-images.githubusercontent.com/65641209/192504912-d2ec1a6b-1429-4c1d-b3a9-92552f3c13d9.png)

copy-icon is working for audit tab -> copy user token

**Comment by pierre** [comment]
Ah weird, maybe it's not valid anymore 🤷 Thanks for checking!
