### ISSUE TITLE
Tag select box too small

### ISSUE THREAD

**Issue by GregOriol** [killbill/killbill-admin-ui#210]
Hi, we are experiencing a problem with the tags select box: it has a max height and is too small when using a few custom tags. This makes impossible to click on the "Update" submit button to save the changes.

<img width="316" alt="capture d ecran 2018-06-13 a 15 23 35" src="https://user-images.githubusercontent.com/3975044/41354235-bd09f512-6f1e-11e8-821c-c05fb9f6f58f.png">

I'd like to suggest a change here: https://github.com/killbill/killbill-admin-ui/blob/933326e7b9cca30ef19ef0e4df8ab1f60c22ba65/app/assets/stylesheets/kaui/tags.less#L63

Instead of `overflow: hidden`, set `overflow: auto`. It should not change or break the normal behavior, but scrollbars will now appear automatically when there are many tags.

**Comment by sbrossie** [comment]
@GregOriol Do you want to submit a PR with the change - have you verified if this works? If so, please submit against our `work-for-release-0.19.x` branch.

**Comment by GregOriol** [comment]
@sbrossie I'd love to submit a PR, but I don't have an environment set up to develop on this project, and therefore cannot really validate it technically, so I didn't make one, even though this one is a very light/simple change. I have though verified that this works with the inspector in browsers. That's why I prefer to suggest the change instead.
