### ISSUE TITLE
Incorrect display amount for JPY

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-admin-ui#242]
See https://github.com/killbill/killbill-admin-ui/blob/16bd331eba0315f1342fee4563e5f7c8c517f9f1/app/models/kaui/base.rb#L5

Reported on the mailing-list: https://groups.google.com/forum/?#!msg/killbilling-users/yzBi17bHshg/7i9nvwtQCQAJ

**Comment by jungipark** [comment]
also korea won same issue
