### ISSUE TITLE
Display external key in payment method dropdown

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-admin-ui#254]
For some plugins, the external key itself is valuable, but we currently only display the _external payment method id_ as returned by the plugin (if it exists).

See https://killbill.github.io/slate/?ruby#payment-method-retrieve-a-payment-method-by-id.

For testing, write a functional test that creates a payment method (plugin name `__EXTERNAL_PAYMENT__`) with a custom external key.

![image](https://user-images.githubusercontent.com/51940/65155925-fa7f6500-d9e2-11e9-8eec-67cf147b7533.png)

**Comment by kpbacode** [comment]
![Screenshot 2022-09-26 at 13 43 14](https://user-images.githubusercontent.com/65641209/192267990-d80b7841-ae61-4488-8a80-686ab97cdba7.png)

to
![Screenshot 2022-09-26 at 15 26 47](https://user-images.githubusercontent.com/65641209/192288681-b2b279f2-5a37-42ef-92db-c540df4576c8.png)

```
curl -v \
     -X POST \
     -u admin:password \
     -H 'Content-Type: application/json' \
     -H 'X-Killbill-ApiKey:bob' \
     -H 'X-Killbill-ApiSecret:lazar' \
     -H 'X-Killbill-CreatedBy: creator' \
     --data-binary '{"pluginName":"__EXTERNAL_PAYMENT__", "externalKey": "paypal", "pluginInfo":{}}' \
     "http://127.0.0.1:8080/1.0/kb/accounts/0de89a97-b09a-4b62-81f4-85c9ef4cb989/paymentMethods?isDefault=true"
```

Do you want only tests or should we add this to Kaui Admin Panel?

**Comment by pierre** [comment]
Yup, we should add it like you have. I was just suggesting how to add a test for it.

We should also rename `Key` to `External ID`, as it can be confusing otherwise: https://github.com/killbill/killbill-admin-ui/blob/29b1c53c8d5319a42dd188c8fb0882ee76ae895c/app/views/kaui/payment_methods/_payment_methods_details_table.html.erb#L13

Thanks!

**Comment by kpbacode** [comment]
External ID should be:  `payment_method.plugin_info.external_payment_method_id` or `payment_method.payment_method_id` ?
External ID is not visible from dropdown.


Now we show `payment_method.payment_method_id`
![Screenshot 2022-09-27 at 11 36 29](https://user-images.githubusercontent.com/65641209/192491415-9eb5bc48-e98e-4440-a819-ddef90e93a59.png)

**Comment by kpbacode** [comment]
Test include:
- [ √] should get new payment method with external key
- [√ ] fail when duplicated external key

added locales:
- [√ ] en.yml

**Comment by reshmabidikar** [comment]
Looks good. If an external key is not specified while creating the payment method, it defaults to the payment method id. (See attached screenshot). This is consistent with other APIs (like account creation, subscription creation, etc.) so all good. 👍 

<img width="435" alt="image" src="https://user-images.githubusercontent.com/85998496/195971696-bd9da1d9-5b05-4cb6-8fde-003b1131ec08.png">

**Comment by reshmabidikar** [comment]
Closing this issue since this works as expected.

**Comment by reshmabidikar** [comment]
Closing this issue since this works as expected.
