### ISSUE TITLE
KAUI Error On Docker

### ISSUE THREAD

**Issue by ditjhaba** [killbill/killbill-admin-ui#269]
I am trying to use the Docker compose file that is on your site and I am getting the below error: 

No such file to load -- java.lang.StackOverflowError: null.rb from org/jruby/RubyKernel.java:956:in `require' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:379:in `block in require_or_load' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:36:in `block in load_interlock' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-5.1.0/lib/active_support/dependencies/interlock.rb:12:in `block in loading' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-5.1.0/lib/active_support/concurrency/share_lock.rb:149:in `exclusive' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-5.1.0/lib/active_support/dependencies/interlock.rb:11:in `loading' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:36:in `load_interlock' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:357:in `require_or_load' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:335:in `depend_on' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:251:in `require_dependency' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-5.1.0/lib/rails/engine.rb:476:in `block in eager_load!' from org/jruby/RubyArray.java:1735:in `each' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-5.1.0/lib/rails/engine.rb:475:in `block in eager_load!' from org/jruby/RubyArray.java:1735:in `each' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-5.1.0/lib/rails/engine.rb:473:in `eager_load!' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-5.1.0/lib/rails/engine.rb:354:in `eager_load!' from org/jruby/RubyArray.java:1735:in `each' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-5.1.0/lib/rails/application/finisher.rb:67:in `block in Finisher' from org/jruby/RubyBasicObject.java:1728:in `instance_exec' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-5.1.0/lib/rails/initializable.rb:30:in `run' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-5.1.0/lib/rails/initializable.rb:59:in `block in run_initializers' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:228:in `block in tsort_each' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:350:in `block in each_strongly_connected_component' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:431:in `each_strongly_connected_component_from' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:349:in `block in each_strongly_connected_component' from org/jruby/RubyArray.java:1735:in `each' from org/jruby/RubyMethod.java:127:in `call' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:347:in `each_strongly_connected_component' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:226:in `tsort_each' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/tsort.rb:205:in `tsort_each' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-5.1.0/lib/rails/initializable.rb:58:in `run_initializers' from /var/lib/tomcat/webapps/ROOT/WEB-INF/gems/gems/railties-5.1.0/lib/rails/application.rb:353:in `initialize!' from /var/lib/tomcat/webapps/ROOT/WEB-INF/config/environment.rb:5:in `<main>' from org/jruby/RubyKernel.java:956:in `require' from uri:classloader:/jruby/rack/rails/environment3.rb:1:in `(root)' from uri:classloader:/jruby/rack/rails/environment3.rb:25:in `load_environment' from uri:classloader:/jruby/rack/rails_booter.rb:83:in `<main>'

**Comment by pierre** [comment]
Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
