### ISSUE TITLE
Invalid dates passed to getQueueEntries

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-admin-ui#272]
The queue screen doesn't pass ISO formatted timestamps when a date filter is specified:

```
1148 > GET http://killbill:8080/1.0/kb/admin/queues?accountId=6c0ab42c-775f-4a74-95d7-f8210b0793c8&withHistory=false&minDate=1970-01-01&maxDate=2020-09-10+14%3A40%3A40+UTC

2020-09-03T14:40:45,488+0000 lvl='WARN', log='LoggingResponse', th='catalina-exec-48', xff='', rId='59071947-0ea3-40b4-9737-8860af6efe5a', tok='', aRId='', tRId='1', Bad request
java.lang.IllegalArgumentException: Invalid format: "2020-09-10 14:40:40 UTC" is malformed at " 14:40:40 UTC"
        at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945)
        at org.killbill.billing.jaxrs.resources.AdminResource.getQueueEntries(AdminResource.java:177)
        at org.killbill.billing.server.modules.JaxRSAopModule$JaxRsMethodInterceptor$1.execute(JaxRSAopModule.java:87)
```

**Comment by kpbacode** [comment]
Pull added: https://github.com/killbill/killbill-admin-ui/pull/315
![Screenshot 2022-09-23 at 14 34 58](https://user-images.githubusercontent.com/65641209/191961467-8f114872-f0f6-4a0f-921a-b15f99b0aa42.png)
![Screenshot 2022-09-23 at 14 36 10](https://user-images.githubusercontent.com/65641209/191961600-07cfaab4-d081-4baa-bf63-f375c87c960b.png)

**Comment by kpbacode** [comment]
To do:

- Tests

**Comment by kpbacode** [comment]
to test:

`http://localhost:3000/queues?account_id=6d37b370-3358-4dee-a3f3-b1620f887e87&with_history=true&min_date=1970-01-01&max_date=2020-09-10+14%3A40%3A40+UTC`

Please change min_date and max_date

Do we need submission form here? 


Note: This code need to be fixed as is checking valid of date format and passing date with time. It should be only time and the iso format is to supply only date without time.

**Comment by kpbacode** [comment]
@reshmabidikar Please postpone tests. I need update this code and add tests.

**Comment by kpbacode** [comment]
https://github.com/killbill/killbill-admin-ui/pull/325

**Comment by kpbacode** [comment]
@pierre Do we need submission form here?

**Comment by reshmabidikar** [comment]
Tested by adding the following URL in the browser:
`http://localhost:3000/kaui/accounts/011020e4-0159-4bdb-85ac-ef0e4f1841db/queues?accountId=011020e4-0159-4bdb-85ac-ef0e4f1841db&withHistory=false&min_date=2021-09-10&max_date=2023-09-10+14%3A40%3A40+UTC`

This does not display any error message. It displays the following screen:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/85998496/196349245-1698414c-398f-40d8-9e9e-b73d581f11c9.png">

Is there any other way to test this?

**Comment by kpbacode** [comment]
Hey!
1. Create subscription for 2022-10-25
2. http://localhost:3000/queues?account_id=f87c5234-1cf7-476f-b3e1-22248487d9b4&min_date=2022-10-25&max_date=2022-10-29
3. When you don't supply with_history param it will be false and you will see only white records not grey records.

This page queue kill bill and return results.
3. http://localhost:3000/queues?account_id=6d37b370-3358-4dee-a3f3-b1620f887e87&with_history=true&min_date=2023-10-10&max_date=2023-11-12 

More about this service here: https://killbill.github.io/slate/index.html?shell=#admin-low-level-view-apis

**Comment by pierre** [comment]
> Is there any other way to test this?

@reshmabidikar The parameters are pre-set by the links at the top of the page, there isn't a way to customize filters today I think (we could consider adding a time filter dropdown though, like in Kanaui: https://github.com/killbill/killbill-analytics-ui/blob/5a08877cdecc7819bda28b349cf614a9ec8acc64/app/views/kanaui/dashboard/index.html.erb#L22).

https://github.com/killbill/killbill-admin-ui/blob/d7d2d49084d0635a3768d005948bf0933df0fe18/app/views/kaui/queues/index.html.erb#L2-L7

**Comment by reshmabidikar** [comment]
The following URLs are now accepted:

- `http://localhost:3000/kaui/accounts/368eb32f-d137-4438-aa68-8acf0da28f48/queues?account_id=368eb32f-d137-4438-aa68-8acf0da28f48&min_date=2022-10-25&max_date=2023-10-19T08:04:38+0000`
- `http://localhost:3000/kaui/accounts/368eb32f-d137-4438-aa68-8acf0da28f48/queues?account_id=368eb32f-d137-4438-aa68-8acf0da28f48cmin_date=2022-10-25&max_date=2023-10-19`

The following URL causes an error:
`http://localhost:3000/kaui/accounts/368eb32f-d137-4438-aa68-8acf0da28f48/queues?account_id=368eb32f-d137-4438-aa68-8acf0da28f48&min_date=2022-10-25&max_date=2023-10-19%3A40%3A40+UTC`
This displays the following:
<img width="888" alt="image" src="https://user-images.githubusercontent.com/85998496/196929976-68117da9-3d77-48fe-85a4-1ab54660ad21.png">
From what I understand, `2023-10-19%3A40%3A40+UTC` should be parsed and its `date` component should be returned.  Could you please confirm @kpbacode?

Secondly, the Kill Bill API uses `minDate` and `maxDate` as parameter names. (See [docs](https://killbill.github.io/slate/#admin-get-queue-entries)), whereas Kaui uses  `min_date` and `max_date`. Can we change the parameter names in Kaui for the sake of consistency?

**Comment by reshmabidikar** [comment]
@pierre I'm still not very clear on the expected behavior on this one. From what I understand, if a user specifies a date like 
`2020-09-10+14%3A40%3A40+UTC` as a query parameter by typing the appropriate Kaui URL in the browser, an error occurs on the Kill Bill side. So, we need to make changes on the Kaui side to not pass such dates. In other words, If a date like `2020-09-10+14%3A40%3A40+UTC` is supplied as a query parameter, Kaui should convert this to something like `2023-10-19T08:04:38` (an ISO formatted date) before sending it to Kill Bill. Does this sound like an accurate summary of the issue?

**Comment by pierre** [comment]
I think we are all good! The original issue was that the links at the top of the page were broken, but they now seem to work.

Regarding `2023-10-19%3A40%3A40+UTC` (`2023-10-19:40:40 UTC`), it's not ISO formatted, so it's ok to reject it.
