### ISSUE TITLE
docker kaui image tag 2.1.0 missing?

### ISSUE THREAD

**Issue by martinlevesque** [killbill/killbill-admin-ui#279]
Hi everyone!

There seems to be a new Kaui version (2.1.0), but it does not seem to be available on docker hub - https://hub.docker.com/r/killbill/kaui/tags?page=1&ordering=last_updated (latest looks like 2.0.8). 

Are all versions typically available on docker hub? @pierre 

Thanks,

**Comment by pierre** [comment]
This is the wrong repository: the published Kaui Docker image is built off of https://github.com/killbill/killbill-admin-ui-standalone.

Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead in the future. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).
