### ISSUE TITLE
Incorrect error message for duplicate overdue configuration

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill-admin-ui#282]
In case a tenant has an overdue configuration and a user tries to upload a new `overdue.xml` file via Kaui, this causes the following error:
`Error while communicating with the Kill Bill server`

(Screenshot attached)

This needs to be fixed to display a better error message.
<img width="946" alt="overdue-upload-kaui-error" src="https://user-images.githubusercontent.com/85998496/130916816-13b354f7-9062-43f2-beb8-5b2cfd4d87db.png">

**Comment by kpbacode** [comment]
Good Morning Reshma,

1. I was able to upload another overdue configuration 
![overdue_upload](https://user-images.githubusercontent.com/65641209/191666443-3e3a8134-b1f2-4c38-b1cf-69eae558a91b.png)

2. When uploading maiflormed xml file, there is error
![Screenshot 2022-09-22 at 06 52 10](https://user-images.githubusercontent.com/65641209/191666540-d1a6a990-d269-4f04-88e3-5200f8271df6.png)

3. I was able to provide better error response by validating XML file using nokogiri gem 
![Screenshot 2022-09-22 at 07 41 42](https://user-images.githubusercontent.com/65641209/191667260-81b1be43-cb6d-4044-b515-2270c5eb5a1e.png)

I need more time to improve code and improve error messages before I do PR.

BTW 
When I ass error text outside XML tags, nokogiri will prase this content even when I set STRICT mode on reading. 
This is important as KillBill will raise error and nokogiri.

![Screenshot 2022-09-22 at 07 43 44](https://user-images.githubusercontent.com/65641209/191667739-0d829cdd-6dad-40bc-ab6b-8dc16f153dc4.png)

**Comment by reshmabidikar** [comment]
I'm not able to reproduce the original issue on my local setup (that does not have the latest Kaui changes) but here are a few observations tested in my WSL2 setup that has the new changes:

## Scenario 1
1. Upload [overdueWithNumberOfUnpaidInvoicesCondition.xml](https://github.com/killbill/killbill-docs/blob/v3/overdue-configurations/overdueWithNumberOfUnpaidInvoicesCondition.xml) - uploads successfully, no error message
2. Click on the "Overdue Show" tab, the overdue configuration is not shown:
<img width="830" alt="image" src="https://user-images.githubusercontent.com/85998496/196939368-6dba6f3b-8c8d-4e40-bbb9-22e72cfe0980.png">
This issue occurs with some of the other catalogs in the https://github.com/killbill/killbill-docs/blob/v3/overdue-configurations directory as well.

## Scenario 2
1. Upload [overdueWithExclusionControlTag.xml](https://github.com/killbill/killbill-docs/blob/v3/overdue-configurations/overdueWithExclusionControlTag.xml) - uploads successfully, no error message
2. Click on the "+" sign next to "Existing Overdue Config" and upload [overdueWithMultipleConditions.xml](https://github.com/killbill/killbill-docs/blob/v3/overdue-configurations/overdueWithMultipleConditions.xml) - uploads successfully.
3. Click on the "Overdue Show" tab, the overdue configuration is not shown.

Also, @pierre, quick question about the expected behaviour for this issue.  If a user tries to upload an overdue configuration for a tenant when one already exists, should Kaui straightway reject this? Or should this be allowed by internally deleting the existing overdue configuration first? I think the second option makes more sense but would like to know your thoughts.

**Comment by reshmabidikar** [comment]
I tested this locally today with the latest `killbill-admin-ui` code and the original issue is reproducible. Steps to reproduce:

1. Click on the "Overdue Show" tab and upload [overdueWithNumberOfUnpaidInvoicesCondition.xml](https://github.com/killbill/killbill-docs/blob/v3/overdue-configurations/overdueWithNumberOfUnpaidInvoicesCondition.xml) - uploads successfully, no error message
2. Click on the "+" sign next to "Existing Overdue Config" 
3. The following screen is displayed:
<img width="883" alt="image" src="https://github.com/killbill/killbill-admin-ui/assets/85998496/02ebd6a9-76d5-4dcc-adcb-5ac16b9f3364">

This needs to be fixed to display a better error message.

@tungleduyxyz, could you please take a look?

**Comment by tungleduyxyz** [comment]
Sure @reshmabidikar. let me take a look.

**Comment by tungleduyxyz** [comment]
Hi @reshmabidikar ,
As I understand, your overdue XML config here: https://github.com/killbill/killbill-docs/blob/v3/overdue-configurations/overdueWithMultipleConditions.xml
In the condition part of the accountOverdueStates, I only see the **numberOfUnpaidInvoicesEqualsOrExceeds** field (missing **timeSinceEarliestUnpaidInvoiceEqualsOrExceeds**, **controlTagInclusion**, **controlTagExclusion**, **totalUnpaidInvoiceBalanceEqualsOrExceeds**), and the current code did not prepare for the empty cases.
I made a pull request here to handle the error: https://github.com/killbill/killbill-admin-ui/pull/362
Please help me to test it.
cc: @pierre

**Comment by pierre** [comment]
> Also, @pierre, quick question unrelated to the above scenarios, I'm wondering what should be the expected behavior for this issue. If a user tries to upload an overdue configuration for a tenant when one already exists, should Kaui straightway reject this? Or should this be allowed by internally deleting the existing overdue configuration first? I think the second option makes more sense but would like to know your thoughts.

Yes, but this is actually already done on the server side, check https://github.com/killbill/killbill/blob/81c8d409fbe47df44b1ae8324289589ac0cc8a3f/overdue/src/main/java/org/killbill/billing/overdue/api/DefaultOverdueApi.java#L67 🙂 

To update an overdue config, the user should be able to just upload a new file and it _should_ just work.
