### ISSUE TITLE
Add validation in custom field form

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-admin-ui#291]
When creating a new custom field, `Object ID` needs to point to a valid object id (`UUID`). We should add validations for this:

* Simplest implementation could be to validate the field is indeed a `UUID`, before the form is submitted.
* A better implementation would be to validate the object exists, similar to what we do when checking duplicate external keys: https://github.com/killbill/killbill-admin-ui/blob/08f6c9abc7e68dc41e68f90b9500eeac1cc44f84/app/assets/javascripts/kaui/kaui.js#L145-L148

**Comment by reshmabidikar** [comment]
On entering a value for the `Object Id` field (a valid value), the following screen is shown:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/85998496/196345605-b8fb4fcb-8a3b-4e83-a498-4a81d4ee5082.png">

**Comment by kpbacode** [comment]
Probably routes are not updated.
https://github.com/killbill/killbill-admin-ui/pull/317/files#diff-959bc9abc46a55332bb64d5155a79323afa75a50ec1a2137ddd22d926f62c6c5

**Comment by reshmabidikar** [comment]
I do have the latest code:https://github.com/reshmabidikar/killbill-admin-ui/blob/d7d2d49084d0635a3768d005948bf0933df0fe18/config/routes.rb#L150 🤔

**Comment by reshmabidikar** [comment]
1. Enter a random string in the "Object Id" field as follows:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/85998496/197175994-e5337769-4f53-4c69-920c-44ee6276b7c9.png">
2. The following screen is displayed:
<img width="910" alt="image" src="https://user-images.githubusercontent.com/85998496/197176353-a4ee99db-6727-46e5-8c53-f7350b790c59.png">

@pierre, looks like there is a bug on the Kill Bill side as well. The system allows entering a valid `ObjectId` (one that exists in the Kill Bill database) against an invalid `objectType`. So, for example, the [Add Custom Field to Subscription](https://killbill.github.io/slate/#subscription-add-custom-fields-to-subscription) endpoint can be invoked with a UUID corresponding to an account and specifying `objectType=SUBSCRIPTION`. The same behavior can be replicated via Kaui as well. If you agree that this is a bug, I will file a separate issue corresponding to this.

**Comment by kpbacode** [comment]
This code can cover this case too. It check for each ObjectType. It won't allow to save without checking if object already exist.
![Screenshot 2022-10-21 at 13 42 02](https://user-images.githubusercontent.com/65641209/197188283-dfdd8993-245d-488e-9fd3-61eade0f4564.png)

**Comment by reshmabidikar** [comment]
Filed https://github.com/killbill/killbill/issues/1786 for the Kill Bill side issue as the API needs to be fixed too.

**Comment by reshmabidikar** [comment]
@kpbacode, looks like this issue is fixed on the Kaui side, could you please confirm? If so, I will close this issue.

**Comment by reshmabidikar** [comment]
Tested this locally with the latest `killbill-admin-ui`/`killbill-admin-ui-standalone` code and it works fine. 

1. On entering an invalid object id, an error message is displayed as follows:

<img width="814" alt="image" src="https://github.com/killbill/killbill-admin-ui/assets/85998496/e01bce27-3008-47ca-ae29-0737ba58b231">

2. On entering an invalid object type, the following screen is seen:

<img width="809" alt="image" src="https://github.com/killbill/killbill-admin-ui/assets/85998496/559369ef-9392-44d3-ade5-4d30f517d2a2">


I think we should revisit 2/ after https://github.com/killbill/killbill/issues/1786 is fixed. Closing this issue for now.
