### ISSUE TITLE
Upgrade d3 to v4

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-admin-ui#30]
As part of this, charting code in kanaui should be refactored and cleaned-up.

Kanaui work tracked by https://github.com/killbill/killbill-analytics-ui/issues/10.

**Comment by sbrossie** [comment]
Closed in c7c797557715d9d0e3f13dfb1dd97f451d169285

**Comment by sbrossie** [comment]
Closed by mistake.

**Comment by pierre** [comment]
Kaui doesn't rely on d3 anymore (https://github.com/killbill/killbill-admin-ui/commit/5ef4301264a60c2519eb10affea283f1a7fa7f1a).
