### ISSUE TITLE
Per-account catalog support when creating bundles

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-admin-ui#309]
It looks like the `accountId` isn't passed when calling the catalog: https://github.com/killbill/killbill-admin-ui/blob/c42aee1fcc7bf2f14849b9336c7dd40373f34402/app/controllers/kaui/subscriptions_controller.rb#L200

See https://github.com/killbill/killbill/blob/3a52a09da73c4e6d06cdb23272e5c070789ca345/jaxrs/src/main/java/org/killbill/billing/jaxrs/resources/CatalogResource.java#L329

Make a pass at all catalog related calls and ensure the `accountId` is always passed.

**Comment by tungleduyxyz** [comment]
Hi @pierre ,
I see the Ruby Client only supports base_product_name here: https://github.com/killbill/killbill-client-ruby/blob/7d80c2dfdc02fc061c270b5bd9e2e81d6646bfff/lib/killbill_client/models/catalog.rb#L16
We need to make a change here to add accountId as a param.

**Comment by tungleduyxyz** [comment]
I made a PR to refactor the instance variable here: https://github.com/killbill/killbill-admin-ui/pull/356/files
The Rubocop will be fine after we merge this PR: https://github.com/killbill/killbill-admin-ui/pull/355
