### ISSUE TITLE
Display the correct amount in payments/invoice payments screen

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill-admin-ui#322]
The Kaui **payments** screen and the **invoice payment** screen display an incorrect amount when the processed amount is different from the actual amount. 

These screens use the  `amount` field from the transaction, not the `processedAmount`  field. 

For example, when the [Retrieve Invoice Payment](https://killbill.github.io/slate/?shell#invoice-retrieve-payments-associated-with-an-invoice) endpoint returns `amount=60` and `processedAmount=10`, Kaui displays `60` as can be seen from the **invoice payment** screenshot below:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/85998496/194532271-752560dc-13e8-400a-9ff9-6cac3589d369.png">

**Proposed Fix:**

When the  `processedAmount`  is different from `amount` , Kaui should show the `processedAmount` followed by a `(?)` symbol. On hovering over the  `(?)` icon, it should display the `amount`.  So, in the example above, it should display `$10 (USD) (?)` and on hover of the small `(?)` icon, it should display `$60 (USD)`

Note that this fix also needs to be applied to the payment screen below. 

<img width="890" alt="image" src="https://user-images.githubusercontent.com/85998496/194532497-14f599f2-9448-48ee-b70f-a07661c52451.png">

**Comment by kpbacode** [comment]
> On hovering over the (?) icon, it should display the amount. 

This is customer requirement to have this effect? Or we can have this listed the same way like other columns?

> Note that this fix also needs to be applied to the payment screen below.

Kaui loads partials templates so this is included anywhere where we load payments_table.

When we go to listing of all payments we see `capture amount` so something has been implemented to show what amount has been captured. 



![Screenshot 2022-10-11 at 11 10 29](https://user-images.githubusercontent.com/65641209/195048901-d1f87fc0-d020-4c28-a136-d5a1e3cc10bb.png)
![Screenshot 2022-10-11 at 11 18 04](https://user-images.githubusercontent.com/65641209/195050606-d92a2a85-28a1-4619-9e88-b81e8ec8cccd.png)
![Screenshot 2022-10-11 at 11 19 08](https://user-images.githubusercontent.com/65641209/195050852-4cdc2746-9f17-43b6-a513-f5c7d22f6cb1.png)

**Comment by reshmabidikar** [comment]
> This is customer requirement to have this effect? Or we can have this listed the same way like other columns?

Could you please elaborate on what you mean by other columns?

> When we go to listing of all payments we see capture amount so something has been implemented to show what amount has been captured.

I do not think we need to change anything here, so the payments screen can continue to display the captured amount. @pierre, any thoughts?

**Comment by kpbacode** [comment]
1. All columns are listed without `?` hover effect, just plain columns with data if there is any and we could implement this the same like others columns. 
2. /accounts/:account_id/payments has not been changed in any way, I just pointed that some info about what amount has been captured is already just not linked to invoice listing.

here is commit for this feature https://github.com/kpbacode/killbill-admin-ui/commits/show-processamount

**Comment by pierre** [comment]
> This is customer requirement to have this effect? Or we can have this listed the same way like other columns?

I don't think we should introduce a new column for that. In 99.9999% of the cases, `amount == processed amount`. So, in most cases, this new column will take space for not much information. We could have a hover effect for that 0.0001% case, just like in the audit screens?

> I do not think we need to change anything here, so the payments screen can continue to display the captured amount. @pierre, any thoughts?

Agreed, auth/capture amounts are a different concept and should be kept as-is.

**Comment by kpbacode** [comment]
[] Need to figure out how to add transaction without different processed amount. 
[] Will add this tool tip at the bottom, to don't cover the amount.

![Screenshot 2022-10-11 at 14 31 20](https://user-images.githubusercontent.com/65641209/195091016-ab0e6a59-486b-4cbb-bbc0-42211e61adaf.png)

**Comment by pierre** [comment]
> Need to figure out how to add transaction with different processed amount.

You mean for testing purposes? If so, you cannot actually. This is returned in corner cases by the payment plugins. You _might_ be able to use the payment test plugin to fake it, but I wouldn't bother.

**Comment by kpbacode** [comment]
> **Proposed Fix:**
> 
> When the `processedAmount` is different from `amount` , Kaui should show the `processedAmount` followed by a `(?)` symbol. On hovering over the `(?)` icon, it should display the `amount`. So, in the example above, it should display `$10 (USD) (?)` and on hover of the small `(?)` icon, it should display `$60 (USD)`

implemented as requested 
![Screenshot 2022-10-12 at 12 42 19](https://user-images.githubusercontent.com/65641209/195324734-36e76d46-3058-4f7a-b862-58a5e0b3db5f.png)

todo:
tests

**Comment by reshmabidikar** [comment]
Did some testing using the [payment test plugin](https://github.com/killbill/killbill-payment-test-plugin). The [Retrieve Payment by Id](https://killbill.github.io/slate/#payment-retrieve-a-payment-using-paymentid) endpoint returns the following data (Different values are returned for `amount` and `processedAmount`):
```
{
  "accountId": "1b5ef030-b380-4d6b-aa35-29c72c7375ff",
  "paymentId": "a70a3127-0ab0-4c6f-897c-faf119acd794",
  "paymentNumber": "2",
  "paymentExternalKey": "a70a3127-0ab0-4c6f-897c-faf119acd794",
  "authAmount": 0,
  "capturedAmount": 0,
  "purchasedAmount": 10,
  "refundedAmount": 0,
  "creditedAmount": 0,
  "currency": "USD",
  "paymentMethodId": "9d24cb12-d95c-4469-9bbe-13c289c7de41",
  "transactions": [
    {
      "transactionId": "d32c1d32-6f01-4180-a813-d06af77e9a9e",
      "transactionExternalKey": "d32c1d32-6f01-4180-a813-d06af77e9a9e",
      "paymentId": "a70a3127-0ab0-4c6f-897c-faf119acd794",
      "paymentExternalKey": "a70a3127-0ab0-4c6f-897c-faf119acd794",
      "transactionType": "PURCHASE",
      "amount": 100,
      "currency": "USD",
      "effectiveDate": "2022-10-27T08:47:01.000Z",
      "processedAmount": 10,
      "processedCurrency": "USD",
      "status": "SUCCESS",
      "gatewayErrorCode": null,
      "gatewayErrorMsg": null,
      "firstPaymentReferenceId": null,
      "secondPaymentReferenceId": null,
      "properties": null,
      "auditLogs": []
    }
  ],
  "paymentAttempts": null,
  "auditLogs": []
}
```

However, Kaui displays the following screen (No question mark icon and nothing shown on hovering the mouse over the `amount` field):
<img width="886" alt="image" src="https://user-images.githubusercontent.com/85998496/198241139-502cbeb9-d252-4508-89c5-15f7d202ca1d.png">

**Comment by kpbacode** [comment]
You are using version with this template updated? 
killbill-admin-ui/app/views/kaui/payments/_payment_table.html.erb              
              
              <% if transaction.amount.present? %>
                  <% if transaction.amount != transaction.processed_amount %>
                  <%= humanized_money_with_symbol Kaui::Transaction.processed_amount_to_money(transaction) %>
                  (<%= transaction.currency %>)
                  <a href="#" data-toggle="tooltip" class="kb-tooltip" title="<%= I18n.translate('requested_amount_colon') %> <%= humanized_money_with_symbol Kaui::Transaction.amount_to_money(transaction) %>(<%= transaction.currency %>)">(?)</a>
                  <% else%>
                  <%= humanized_money_with_symbol Kaui::Transaction.amount_to_money(transaction) %>
                  (<%= transaction.currency %>)
                  <% end %>
              <% end %>

**Comment by reshmabidikar** [comment]
Yes, I had the correct code but my `killbill-admin-ui-standalone` code was not pointing to the local `killbill-admin-ui` code. On fixing this, it works fine. I see the following payment screen:

<img width="875" alt="image" src="https://user-images.githubusercontent.com/85998496/198463204-69059a54-7685-43a9-93e9-ca2367136917.png">

The invoice payment screen also works as expected.
