### ISSUE TITLE
Some Overdue Issues

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill-admin-ui#326]
## After uploading an overdue configuration, the "Catalog Show" tab is displayed
1. Upload an overdue configuration
2. This displays the "Catalog Show" tab as follows:
<img width="901" alt="image" src="https://user-images.githubusercontent.com/85998496/196944539-36e4eb69-dd8e-4163-b592-e1e126329348.png">
The "Overdue Show" tab should be displayed.

## Overdue configuration not displayed
1. Click on the "Overdue Show" tab
4. Click "View Overdue Xml". 
5. This displays the following screen:

<img width="892" alt="image" src="https://user-images.githubusercontent.com/85998496/196943462-083333f0-322d-41cc-96e4-4839ad134c96.png">

## Validation required while uploading overdue configuration
1. Click on the "Overdue Show" tab
2. Click on the "+" sign next to "Existing Overdue Config"
3. Click on "Enable Advanced Configuration (Upload XML)"
6. Click on the "Upload" button without selecting a file. 
7. This displays the following screen:
<img width="904" alt="image" src="https://user-images.githubusercontent.com/85998496/196944117-e53ffec9-5788-4ecb-80a5-50fbb0a5086f.png">
It should not be possible to click the "Upload" button without selecting a file

**Comment by tungleduyxyz** [comment]
Hi @reshmabidikar, Is it okay to use a default warning like this when no file is selected?
<img width="1322" alt="image" src="https://github.com/killbill/killbill-admin-ui/assets/80109474/55de5437-feda-49e7-ba6c-ed8fee62afce">

**Comment by pierre** [comment]
Looks good to me. These are the built-in HTML5 warnings, right? As long as there is wide browser support, :shipit:

**Comment by tungleduyxyz** [comment]
Yes, that's a default HTML warning. 
Thank you, let me push the code.

**Comment by reshmabidikar** [comment]
Verified that a warning message is displayed  if the "upload" button is clicked without selecting a file in the `Catalog Show`, `Invoice Template`, `Invoice Translation` and `Catalog Translation` tabs too.

**Comment by tungleduyxyz** [comment]
Hi @reshmabidikar, I have updated the code.
Please help me to test the first issue again.
Thank you.

**Comment by reshmabidikar** [comment]
Tested this again and works fine. So after uploading an overdue configuration, the `Overdue Show` tab is displayed.
