### ISSUE TITLE
Price Override field allows negative values

### ISSUE THREAD

**Issue by KBbitsP** [killbill/killbill-admin-ui#327]
When creating a new subscription, the price override field allows negative values. The subscription however is created with the correct value ( striping the negative sign ). 

![image](https://user-images.githubusercontent.com/75751774/198878625-33f61d5a-670c-4433-96fd-1e5d458a7daa.png)

**Comment by tungleduyxyz** [comment]
Hi @pierre , a small question about this ticket.
Do we have any page where I can view the override price here? 
<img width="1066" alt="image" src="https://github.com/killbill/killbill-admin-ui/assets/80109474/ae40033e-47d7-49f7-9d1d-878338f9165e">

Cause after I updated the override price, I can not see it anywhere, the update page always shows blank
