### ISSUE TITLE
Moving the clock via Kaui sets the time to the current time

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill-admin-ui#334]
Steps to reproduce:
1. Click on the gear icon at the top and click `Admin`
2. Specify any date (like `2023-03-24`) and click `Submit`
3. Kaui appends the current time to the specified date (like ` 2023-03-24T09:08:13+00:00`) and sends it to the backend. 
**Expected Behavior**: Kaui should just send the date string (like `2023-03-24`) to the backend.

**Comment by tungleduyxyz** [comment]
Hi @reshmabidikar , 
Here is the result after I submit the new date: 
<img width="1113" alt="image" src="https://github.com/killbill/killbill-admin-ui/assets/80109474/04ff8f63-f7e0-41a2-8933-dc4acbcd19ff">

I think your ticket is about the notice: **Clock was successfully updated to 2023-05-17T01:17:48+00:00**
But here is the data client sent to the backend: 
<img width="1151" alt="image" src="https://github.com/killbill/killbill-admin-ui/assets/80109474/f829fe0b-c53a-49b9-9a9d-6e6aa39ea3f1">
It's only 2023-05-17. So there is confusion here when the client displays the notice, it should be **Clock was successfully updated to 2023-05-17** instead.
If you agree, I can update the notice.
Thank you.

**Comment by reshmabidikar** [comment]
Hi @tungleduyxyz, looks like the date is sent as a query parameter. I see the following request being received on the Kill Bill server side: `POST http://127.0.0.1:8080/1.0/kb/test/clock?requestedDate=2023-05-30T02%3A30%3A40%2B00%3A00&timeoutSec=10`. Could you please confirm if that is the case? Thanks!

**Comment by tungleduyxyz** [comment]
Thanks @reshmabidikar.
I got your point.
The UI only sent the 2023-05-17 date, but we have the logic from KillbillAdminUI backend to convert the date from **2023-05-17** to **2023-05-17T03:14:50+00:00** before sending the request to KillBill service(127.0.0.1:8080).
So I will make a change to update this logic, keeping the date as simple version **2023-05-17**
cc: @pierre
