### ISSUE TITLE
Invoice dry run UI not displayed for user with invoice:dry_run permission

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill-admin-ui#335]
Steps to reproduce:

1. Create a role with the `invoice:dry_run` permission.
2. Create a user and assign the role created above.
3. Log in to Kaui using the user name created above.
4. Open the accounts screen for any account. The Trigger Invoice Dry run UI is not displayed (See screenshot below)
<img width="921" alt="image" src="https://user-images.githubusercontent.com/85998496/225839189-6fa3827f-1180-439d-97f6-4d26452aa4fa.png">

**Expected behavior:** Since the user has permission to trigger an invoice dry run, the UI should be displayed.

Looking at the code [here](https://github.com/killbill/killbill-admin-ui/blob/a1cf9201eb0239886f50da9a080ede1bce18b371/app/views/kaui/accounts/_billing_info.html.erb#L113), looks like the `invoice:trigger` permission is required for the UI to be displayed.

**Comment by kpbacode** [comment]
Available Roles:  https://github.com/killbill/killbill-api/blob/master/src/main/java/org/killbill/billing/security/Permission.java

**Comment by kpbacode** [comment]
@reshmabidikar can you check if this is working for you?

**Comment by KBbitsP** [comment]
Issue fixed here https://github.com/killbill/killbill-admin-ui/pull/385. Tested OK!
