### ISSUE TITLE
Catalog validation

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-admin-ui#347]
Use the new catalog validation endpoint (see https://github.com/killbill/killbill/issues/1674) to validate the catalog before upload. That way, we can improve the current error reporting:
<img width="1204" alt="image" src="https://github.com/killbill/killbill-admin-ui/assets/51940/0a609195-fb1d-478f-8164-993cf65cde95">

**Comment by tungleduyxyz** [comment]
Hi @pierre I created a PR to handle this issue: https://github.com/killbill/killbill-admin-ui/pull/396
Please help me review it. Thanks
