### ISSUE TITLE
Question: Kaui docker tag.

### ISSUE THREAD

**Issue by Aegis8** [killbill/killbill-admin-ui#351]
Hello,

Great to see some activity on kaui!

I saw that the images were updated 10 days ago, but that the tag is still 2.0.11. We have been using this for several months already.

Is there a specific reason that the tag was not bumped?

**Comment by pierre** [comment]
We sometimes re-generate Docker images, when the base OS image has updates (e.g. Ubuntu security updates). The version of Kaui hasn't changed in this image.

**Comment by Aegis8** [comment]
Ok, understood. Thank you for the info.
