### ISSUE TITLE
Show datepicker when creating a subscription at a given date

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-admin-ui#359]
Clicking on Date field doesn't show the datepicker like on other screens
<img width="820" alt="image" src="https://github.com/killbill/killbill-admin-ui/assets/51940/d795c931-1308-4a96-a35a-8116f74322c5">

**Comment by KBbitsP** [comment]
Issue fixed here https://github.com/killbill/killbill-admin-ui/pull/384. Tested OK!
