### ISSUE TITLE
Invoice search by number

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-admin-ui#366]
* [ ] Add a new route to redirect `/invoices/1234` to the invoice 1234 page
https://github.com/killbill/killbill-admin-ui/blob/367aade3abf7a4bf10ea1767094e1e7c59c52e26/config/routes.rb#L101
* [ ] Extend advanced search modal to search for a invoice number
<img width="573" alt="image" src="https://github.com/killbill/killbill-admin-ui/assets/51940/ef7da0ef-500e-4f78-a2e5-9ff0fcdcb90e">

**Comment by hmnhf** [comment]
@pierre Can I make a PR for this?

**Comment by pierre** [comment]
Sure thing! We already have a `find_by_number` API in the client, so this should be pretty straightforward 😊
