### ISSUE TITLE
Control tags are not appearing in account information section

### ISSUE THREAD

**Issue by grana-equinix** [killbill/killbill-admin-ui#376]
Steps to reproduce:

1. Go to any Account via search or from the **latest billing account** link on the dashboard.
2. Click on the tag icon under account information
3. Observe the tag list it only shows users' tags and not Control tags.

Below are the screenshots to understand the flow

<img width="1284" alt="Screenshot 2023-09-14 at 1 07 23 PM" src="https://github.com/killbill/killbill-admin-ui/assets/138654702/97f02fde-22f9-4eae-ac44-013d6575b02d">
<img width="1279" alt="Screenshot 2023-09-14 at 1 07 34 PM" src="https://github.com/killbill/killbill-admin-ui/assets/138654702/26df86e8-b9a0-481c-8e85-66b55173c1b3">
<img width="1287" alt="Screenshot 2023-09-14 at 1 07 59 PM" src="https://github.com/killbill/killbill-admin-ui/assets/138654702/661f172d-91ec-4f84-a3c0-2c65d20d1752">
<img width="1310" alt="Screenshot 2023-09-14 at 1 08 13 PM" src="https://github.com/killbill/killbill-admin-ui/assets/138654702/b97e60d9-7963-4289-97c0-6c6a344650ba">

**Expected behaviour:** All Control tags should load along with users' tags as shown below
<img width="1182" alt="Screenshot 2023-09-14 at 2 10 24 PM" src="https://github.com/killbill/killbill-admin-ui/assets/138654702/433308f0-6cf5-4cf1-b7cf-6da9096d8883">

looking in code [here](https://github.com/killbill/killbill-admin-ui/blob/master/app/models/kaui/tag_definition.rb#L28) which has changed after [RuboCop update commit](https://github.com/killbill/killbill-admin-ui/commit/73dd07774a63b841b957e96183514c6f42758ada).

Old code: 
` ALL_OBJECT_TYPES.each do |object_type|
    define_singleton_method "all_for_#{object_type.downcase}" do |options_for_klient|
      (self.all('NONE', options_for_klient).delete_if { |tag_definition| !tag_definition.applicable_object_types.include? object_type || tag_definition.is_control_tag }).sort
    end
  end`

New code after rubocop change: 
`ALL_OBJECT_TYPES.each do |object_type|
      define_singleton_method "all_for_#{object_type.downcase}" do |options_for_klient|
        (all('NONE', options_for_klient).delete_if { |tag_definition| !tag_definition.applicable_object_types.include?(object_type) || tag_definition.is_control_tag }).sort
      end
    end`

**Comment by pierre** [comment]
It looks like the code before was:

```
!tag_definition.applicable_object_types.include?(object_type) || tag_definition.is_control_tag
```

and now it is:

```
!tag_definition.applicable_object_types.include? object_type || tag_definition.is_control_tag
```

Precedence of `||` and lack of parens is probably the culprit. Good catch!

@grana-equinix Could you try to add the parens again and verify the fix? If it works, can you submit a PR? Thanks!

**Comment by grana-equinix** [comment]
> It looks like the code before was:
> 
> ```
> !tag_definition.applicable_object_types.include?(object_type) || tag_definition.is_control_tag
> ```
> 
> and now it is:
> 
> ```
> !tag_definition.applicable_object_types.include? object_type || tag_definition.is_control_tag
> ```
> 
> Precedence of `||` and lack of parens is probably the culprit. Good catch!
> 
> @grana-equinix Could you try to add the parens again and verify the fix? If it works, can you submit a PR? Thanks!

Its other way now code is `!tag_definition.applicable_object_types.include?(object_type) || tag_definition.is_control_tag`
