### ISSUE TITLE
Showing All Accounts table's pagination is not working

### ISSUE THREAD

**Issue by grana-equinix** [killbill/killbill-admin-ui#388]
Steps to reproduce:

Go to [Show All Account](http://localhost:9090/accounts) page via clicking on link highlighted below from [home](http://localhost:9090/home).

<img width="1100" alt="Screenshot 2023-12-04 at 7 03 36 PM" src="https://github.com/killbill/killbill-admin-ui/assets/138654702/529641e5-6487-497e-9b0f-e07ba1f452c9">

Observe the page as shown below

- Lots of white space on lefthand side
- Pagination is not working

<img width="1293" alt="Screenshot 2023-12-04 at 7 05 48 PM" src="https://github.com/killbill/killbill-admin-ui/assets/138654702/3337bf72-7a97-4713-ab6f-1591f38f02a6">

This is happening  only in the below case:

if `@max_nb_records = nil` in index method of [account_controller.rb](https://github.com/killbill/killbill-admin-ui/blob/master/app/controllers/kaui/accounts_controller.rb#L23) then in account's view [index.html.erb](https://github.com/killbill/killbill-admin-ui/blob/master/app/views/kaui/accounts/index.html.erb#L66) throw $ is not a function error in browser due to the line ` $(".next.paginate_button").toggleClass("disabled", noMoreData);`

**Comment by KBbitsP** [comment]
Hi @grana-equinix 

We are adding the fix for the issue with the white space on the left. Regarding the pagination, this is by design and happens only if the number of records exceed the default pagination threshold of 20K. It is the same behavior across all the tables.
