### ISSUE TITLE
Plan not displayed in Kaui

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill-admin-ui#404]
**Steps to reproduce:**

1. Set the date to `2021-01-01`
2. Upload the [retire-plan-v1.xml](https://github.com/killbill/killbill-docs/blob/5a61ac1957f9174fd4e291c7b61a17c186194388/catalogs/retire-plan/retire-plan-v1.xml) ( Has `standard-weekly` and `standard-monthly` plans) and [retire-plan-v2.xml](https://github.com/killbill/killbill-docs/blob/5a61ac1957f9174fd4e291c7b61a17c186194388/catalogs/retire-plan/retire-plan-v2.xml)  (Has only `standard-weekly` plan) catalogs
3. Create a new account
4. Click on the `Subscriptions` tab and the plus sign next to subscription bundle - Only the `standard-weekly` plan is displayed.

<img width="610" alt="image" src="https://github.com/killbill/killbill-admin-ui/assets/85998496/3e35c42e-2669-4617-b3b3-bd617ee7ca75">

 **Expected behavior:** Since `retire-plan-v1.xml` is effective, the `standard-monthly` plan should also be displayed in the `Plan` drop-down and it should be possible to create a subscription corresponding to the  `standard-monthly` plan. It is possible to create a subscription to the `standard-monthly` plan via the [Create Subscription API endpoint](https://killbill.github.io/slate/subscription.html#create-a-subscription).

**Comment by tungleduyxyz** [comment]
Hi @reshmabidikar ,
I have checked this case and see KAUI is using this Killbill API to get the plan list: /catalog/availableBasePlans
But I see it returns only 1 plan(standard-weekly), like the KAUI displayed, not both standard-weekly and standard-monthly, as you mentioned.

**Comment by reshmabidikar** [comment]
This does indeed look to be an issue on the KB side. I've filed https://github.com/killbill/killbill/issues/2063 to track this issue. Closing this ticket.
