### ISSUE TITLE
Remove bootsnap dependency

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-admin-ui#416]
For Kaui to run on jdk17 (https://github.com/killbill/killbill-cloud/pull/280), I had to remove bootsnap from Gemfile.lock. I'm not quite sure if it's related to https://github.com/Shopify/bootsnap/issues/162, but the exact same war runs on jdk11 but doesn't start on jdk17. 🤷 

Let's remove the dependency.

* Is removing it from https://github.com/killbill/killbill-admin-ui/blob/142793959014650ce4c89348a803da34c8562c84/kaui.gemspec#L26 enough?
* Otherwise, https://jeremy.wadsack.com/2018/10/05/disable-rails-bootsnap-in-production/ might help?

For testing, ensure `bootsnap` isn't present in the final killbill-admin-ui-standalone Gemfile.lock.

**Comment by reshmabidikar** [comment]
Verified that the `Gemfile.lock` in the latest war file no longer includes the bootsnap dependency. Closing this ticket.
