### ISSUE TITLE
Table data in a single line.

### ISSUE THREAD

**Issue by tungleduyxyz** [killbill/killbill-admin-ui#421]
Following this: https://killbillio.slack.com/archives/C05815KTA8L/p1730102942213489?thread_ts=1730092183.932909&cid=C05815KTA8L

Request: Display long text in a single line

**Comment by tungleduyxyz** [comment]
https://github.com/user-attachments/assets/39246c5f-66d4-43ad-890c-a91ff78cd70f
https://github.com/user-attachments/assets/05f32a61-4bee-4bcf-ad35-b27429c05a17

**Comment by tungleduyxyz** [comment]
https://github.com/user-attachments/assets/70a6eda7-2c9c-4b0c-a781-de31175f39f4
https://github.com/user-attachments/assets/2d0892b6-015c-4be1-8e36-be2c8af854a0

**Comment by reshmabidikar** [comment]
Tested this with the latest war file and found that the following issues are addressed:

1. Data is not wrapped
2. Invoice number column is not duplicated
3. Bundle Keys is removed from Invoices table
4. Total Authed Amount, Paid Amount, Returned Amount columns are removed from Payments table

Merging PRs https://github.com/killbill/killbill-admin-ui/pull/424 and https://github.com/killbill/killbill-admin-ui/pull/427 and closing this ticket.

**Comment by reshmabidikar** [comment]
Reopening due to merge conflict in https://github.com/killbill/killbill-admin-ui/pull/427.

**Comment by reshmabidikar** [comment]
Merged https://github.com/killbill/killbill-admin-ui/pull/427, closing this ticket.
