### ISSUE TITLE
Overall Performance

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-admin-ui#46]
Loading and account page takes multiple seconds and a timeline page can easily take between 10-15 seconds for an account with a substantial number of objects.

The task is NOT to optimize the KB requests but to understand what we do on the Rails app (and also investigate whether or not we could make independent requests in parallel. For instance all of the requests for the account page could happen in parallel:
- Retrieve account state
- Retrieve bundles
- Retrieve overdue status
- Retrieve tags
- Retrieve payment methods

**Comment by brickcap** [comment]
Is this issue still valid? I was just looking at the kill bill online demo and neither the account page not the timeline page took 10-15 sec. Infact on a slow connection the entire page loaded within 8 secs (on hard refresh) with most of the time being taken by assets like logo,favicon and icons.

**Comment by pierre** [comment]
Yes, this is still valid but only affects very large deployments (the demo doesn't have a lot of data).

**Comment by pierre** [comment]
Lots of improvements checked-in in `master`.
