### ISSUE TITLE
Bundles screen doesn't support subscriptions started in the future

### ISSUE THREAD

**Issue by pierre** [killbill/killbill-admin-ui#56]
Some fields can be [nil](https://github.com/killbill/killbill/blob/843f9dee6e77580bf2e6b2f192d0522dc1778792/jaxrs/src/main/java/org/killbill/billing/jaxrs/json/SubscriptionJson.java#L316).

![image](https://cloud.githubusercontent.com/assets/51940/11827530/9d4a0b8c-a341-11e5-953d-8328c8ef097c.png)

**Comment by sbrossie** [comment]
I just tried it and this seems to work fine:

![screen shot 2016-12-29 at 3 22 21 pm](https://cloud.githubusercontent.com/assets/246910/21556977/a2fddfc6-cdda-11e6-8cac-05ad3f34746e.png)

Should we close?

**Comment by pierre** [comment]
Yup, this was fixed by https://github.com/killbill/killbill/commit/c0ef729ef5d46e76633ae378e732776ec5f23835.
