### ISSUE TITLE
Add UI support for per-subscription BCD

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-admin-ui#64]
See killbill/killbill#546. Exact work is TBD.

**Comment by sbrossie** [comment]
** Display**

Today the `Billing Info` section displays the (Account) `Bill cycle day`.  Suggestions:
* We modify test in  `Billing Info` section  to call it `Default Account BCD`
* In the subscription table we add a column BCD which shows the BCD associated with this subscription (at a given time) (It could be equal to default `Default Account BCD` if subscription is account aligned or computed from other alignment or finally be overridden based on per-subscription  BCD.

** Modify **

In the action section add a new verb `BCD Overwrite`. Questions:
* Should we compact all actions into one menu ? and keep the 3 verbs?
* Would it make sense to make such action not so visible (i expect should be a rarer case than cancellation)?

**Comment by pierre** [comment]
> Should we compact all actions into one menu ? and keep the 3 verbs?

I would keep separate links for change / cancel (see also my other [comment](https://github.com/killbill/killbill-admin-ui/issues/71#issuecomment-269751251)).

> Would it make sense to make such action not so visible (i expect should be a rarer case than cancellation)?

Indeed, I would guess the BCD is most often set at creation time only. How about putting the link below the transfer option?

![image](https://cloud.githubusercontent.com/assets/51940/21562891/57b71d28-ce31-11e6-8ec6-82564d468f9a.png)

Making it hidden would also prevent abuse and mis-use (e.g. one changing the BCD to fix the invoicing state).

**Comment by sbrossie** [comment]
Actually, i don;t think this will work, because the BCD change api is at the subscription level (not bundle level), so probably should be part of 'Actions' in the subscription row ?

**Comment by sbrossie** [comment]
Closed with 3a6b1758, 9e2c102, 5e9477ff and df0629bfa158
