### ISSUE TITLE
Add support for account notes

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-admin-ui#71]

**Comment by sbrossie** [comment]
The main question is where do we display that?

The notes are set to be `varchar(4096)` (which can be quite large). Using the main `Account Information` might not be such a good place. Maybe something not visible by default and is user clicks we display such notes?

**Comment by pierre** [comment]
There is a large blank space below the timezone today. How about displaying them in a text area there (overflow would trigger scrollbars)?

![image](https://cloud.githubusercontent.com/assets/51940/21562686/b02d54ce-ce2f-11e6-8518-c9a3513ba2ce.png)

> Maybe something not visible by default and is user clicks we display such notes?

We've had reports in the past mentioning that too many actions (e.g. tags) are hidden behind dropdowns, etc. which impacts the productivity of support teams, so I would be reluctant hiding the notes behind a button/link.

Also, my guess is that these notes will most likely always be short (e.g. `VIP customer, impacted 3 times last month by outages, be nice!`).

**Comment by sbrossie** [comment]
Should be fixed with fd89a3532f525a0997060f5e1322501a398dbd5d
