### ISSUE TITLE
How can I configure database?

### ISSUE THREAD

**Issue by jmj4you** [killbill/killbill-admin-ui#77]
hi, 
I am new in Ruby. I trying to use KillBill-admin-ui. I am following readMe  and I got the following error after this command `rake db:migrate`;

Could you please help me to resolve the issue.

joseph@joseph-Satellite-C850:~/projects/killbill-admin-ui/test/dummy$ rake db:migrate
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /var/lib/gems/2.2.0/gems/less-rails-2.7.1/lib/less/rails/railtie.rb:15)
DEPRECATION WARNING: You are using the a deprecated processor interface Less::Rails::ImportProcessor.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /var/lib/gems/2.2.0/gems/less-rails-2.7.1/lib/less/rails/railtie.rb:20)
rake aborted!
ActiveRecord::NoDatabaseError: Unknown database 'kaui'

**Comment by pierre** [comment]
> ActiveRecord::NoDatabaseError: Unknown database 'kaui'

It sounds like the database isn't setup. But if you are not actively working on Kaui, you most likely want to use https://github.com/killbill/killbill-admin-ui-standalone instead.

Please use the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) for support questions.
