### ISSUE TITLE
Account info mandatory fields

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-admin-ui#83]
The account form in Kill Bill has a lot fields but very few are actually required.

It would be nice to either/or:
* Indicate which fields are required (and maybe group those in a section or sequentially
* Maybe only display those by default (form could have a + sign to add extra fields ?)

Also see killbill/killbill#686

**Comment by pierre** [comment]
Only the `time_zone` is mandatory nowadays and the form already defaults to `UTC`. No other field is required anymore.
