### ISSUE TITLE
account.time_zone + stripe.add_payment_method + kaui

### ISSUE THREAD

**Issue by galenp** [killbill/killbill-admin-ui#90]
Hi Guys,

* fresh tenant with stripe plugin
* created account in kaui with my details
* this populated accounts.time_zone with '+08:00'

`
MariaDB [killbill]> select id, time_zone from accounts;
`
`
| 1d484b0a-5e7b-4ee8-b5d6-a6893db879a5 | +08:00    |
`

* created a subscription with addons
* attempted to register a payment method

> 20 > POST http://10.1.1.150:8080/1.0/kb/accounts/1d484b0a-5e7b-4ee8-b5d6-a6893db879a5/paymentMethods
20 > x-killbill-apisecret: test2secret
20 > x-killbill-apikey: test2
20 > x-killbill-createdby: pc-creditcardpaymentprocessmanager
20 > x-killbill-comment: Card ending in 8431
20 > x-killbill-reason: Credit card securely stored with Stripe
20 > accept: application/json, text/html
20 > authorization: Basic YWRtaW46cGFzc3dvcmQ=
20 > user-agent: RestSharp/105.0.1.0
20 > content-type: application/json
20 > host: 10.1.1.150:8080
20 > content-length: 331
20 > accept-encoding: gzip, deflate
20 > 

> 
> 2017-03-13T02:24:38,485+0000 lvl='WARN', log='KillbillLogWriter', th='Thread-11', xff='', rId='8e48d6ab-3d5b-4fb2-8de5-21e62997d819', aRId='12', tRId='4', [stripe-plugin] Failure in add_payment_method: Invalid identifier
> /var/lib/killbill/bundles/plugins/ruby/killbill-stripe/4.1.0/ROOT/gems/gems/tzinfo-1.2.2/lib/tzinfo/zoneinfo_data_source.rb:208:in `load_timezone_info'
> /var/lib/killbill/bundles/plugins/ruby/killbill-stripe/4.1.0/ROOT/gems/gems/tzinfo-1.2.2/lib/tzinfo/timezone.rb:92:in `get'
> /var/lib/killbill/bundles/plugins/ruby/killbill-stripe/4.1.0/ROOT/gems/gems/killbill-8.3.0/lib/killbill/gen/api/account.rb:170:in `to_ruby'
> /var/lib/killbill/bundles/plugins/ruby/killbill-stripe/4.1.0/ROOT/gems/gems/killbill-8.3.0/lib/killbill/gen/api/account_user_api.rb:100:in `get_account_by_id'
> /var/lib/killbill/bundles/plugins/ruby/killbill-stripe/4.1.0/ROOT/lib/stripe/api.rb:103:in `add_payment_method'
> /var/lib/killbill/bundles/plugins/ruby/killbill-stripe/4.1.0/ROOT/gems/gems/killbill-8.3.0/lib/killbill/gen/plugin-api/payment_plugin_api.rb:443:in `addPaymentMethod'
> Killbill$$Plugin$$Api$$PaymentPluginApi_1835118125.gen:13:in `addPaymentMethod'

* after updating accounts.time_zone directly in mySQL to 'UTC' things worked.

At a guess ... Is KAUI using an unexpected format for time_zones that the rest of the system doesn't support?

Thanks

**Comment by pierre** [comment]
Hi @galenp,

This is indeed a known issue when using Kaui and Ruby plugins. See https://github.com/killbill/killbill-plugin-framework-ruby/issues/54 and https://github.com/killbill/killbill-admin-ui/issues/62.
