### ISSUE TITLE
Space in search string generates error message 

### ISSUE THREAD

**Issue by blackdoubt** [killbill/killbill-admin-ui#92]
When a space is included in a search string, an error is generated and no search results are provided. 

Only exhibiting when space is at the start of the search string or between two other characters. 

For example, in the case of searching a user by full name "John Doe" will generate an error. 

![image](https://cloud.githubusercontent.com/assets/10077830/26268362/f1a79256-3ca3-11e7-9046-62b29800dc0a.png)

**Comment by pierre** [comment]
Could you share your [system information](https://github.com/killbill/killbill/wiki/Production-troubleshooting#debugging-issues)?

I am unable to reproduce it, see http://demo.killbill.io/accounts?q=Karley+Lowe for instance. FWIW, we also have a [test](https://github.com/killbill/killbill-admin-ui/blob/5ae476a0485dedacd046b261fc266509228cd3f8/test/functional/kaui/home_controller_test.rb#L7) for this specifically.

**Comment by blackdoubt** [comment]
Not an issue in latest version.
