### ISSUE TITLE
Display associated custom fields on account/invoice/... pages

### ISSUE THREAD

**Issue by GregOriol** [killbill/killbill-admin-ui#93]
Would be nice to display associated custom fields on each type's pages (account/invoice/...), or at least link to them somehow.

**Comment by pierre** [comment]
👍

Maybe we could display them in a similar fashion as the tags dropdown, to avoid cluttering the pages?

**Comment by pierre** [comment]
Done for accounts, invoices, and payments. For bundles and subscriptions, we need a new bulk API on the Kill Bill side.

**Comment by pierre** [comment]
Done for bundles (requires Kill Bill 0.18.13+).

For subscriptions, we don't have a good place in the UI to display them today (and we don't display subscriptions tags either). Punting for now.
