### ISSUE TITLE
Search by object id on custom fields list

### ISSUE THREAD

**Issue by GregOriol** [killbill/killbill-admin-ui#94]
It would be nice to be able to search by object id on the custom fields list, for example to find all custom fields associated with an account/invoice/...

Maybe even have a more complex search functionality like searching by object id and name?

**Comment by pierre** [comment]
> It would be nice to be able to search by object id on the custom fields list, for example to find all custom fields associated with an account/invoice/...

I believe it's as easy as updating [this query](https://github.com/killbill/killbill/blob/71ced4771fe544fbb669b59d00a72d9094b1ddd6/util/src/main/resources/org/killbill/billing/util/customfield/dao/CustomFieldSqlDao.sql.stg#L55-L60).

> Maybe even have a more complex search functionality like searching by object id and name?

Do you have a use-case for an object having lots of custom fields?

**Comment by pierre** [comment]
> I believe it's as easy as updating [this query](https://github.com/killbill/killbill/blob/71ced4771fe544fbb669b59d00a72d9094b1ddd6/util/src/main/resources/org/killbill/billing/util/customfield/dao/CustomFieldSqlDao.sql.stg#L55-L60).

https://github.com/killbill/killbill/commit/b0e9795c9f9b29fd455cf47d5e2dd10f61b1a5cd actually gives us now a superior API (more performant).

I believe https://github.com/killbill/killbill-admin-ui/issues/93 solves this search issue as well (go to the account, invoice or bundles screen first, which will now list all custom fields). If not, feel free to re-open with more details.
