### ISSUE TITLE
Can't type in the amount of Add New Credit

### ISSUE THREAD

**Issue by GregOriol** [killbill/killbill-admin-ui#95]
In the "Add New Credit" form (on an account), it is currently impossible for me to type the amount.

The issue is reproduced on Safari (10), Firefox and Chrome.

I guess this issue has something to do with a french keyboard. When I try to type in numbers (shit+& = 1 on a french keyboard), nothing happens. When I just press &, an "&" appears in the field.
I can't type letters though.

How is the validation done on those fields?

(quickfix: switch system keyboard to american...)

**Comment by pierre** [comment]
Interesting...

The logic is from https://github.com/killbill/killbill-admin-ui/blob/5ae476a0485dedacd046b261fc266509228cd3f8/app/views/kaui/credits/_form.html.erb#L42-L44 and https://github.com/killbill/killbill-admin-ui/blob/0ee9df40a048f4b5331cfd9e0b93e0500ae839ce/app/assets/javascripts/kaui/validation.js#L3-L21.

This is really old code, there are now more modern ways of doing these things. Could you verify that switching to `number_field` for instance fixes it (see https://github.com/killbill/killbill-admin-ui/blob/5e9477ff172cdae655e6c2ace80b3ace3db74486/app/views/kaui/subscriptions/edit_bcd.erb#L12 for an example)?

**Comment by GregOriol** [comment]
Well, there indeed is no perfect solution for this.

Checking the keyCode is quite common, but bad idea as it depends too much on the keyboard configuration: on my french keyboard, & is keyCode 49, 1 is shift+keyCode 49. But on an english keyboard, it might be the opposite. And of course removing the check on "event.shiftKey" (https://github.com/killbill/killbill-admin-ui/blob/0ee9df40a048f4b5331cfd9e0b93e0500ae839ce/app/assets/javascripts/kaui/validation.js#L17) might fix it for me, but will allow special characters for others...

The `number_field` doesn't help either: I checked the BCD form and I can actually type anything in there on Safari/Firefox (letters, special characters, ...), Chrome seems to be the only one to enforce valid numbers.

A somehow "better" way of dealing with all these would be to validate the content of the field instead of the typing, something like:
```
$('#myinput').on('change keyup', function (event) {
    var ckeckChars = /[^0-9.]/gi;
    if(ckeckChars.test(event.target.value)) {
        event.target.value = event.target.value.replace(ckeckChars,'');
    }
});
```
or with a different syntax: https://stackoverflow.com/a/21215126/1940799

It's not perfect as the user sees the invalid character in the field and then it disappears, but still better than not being able to type...

What do you think?

**Comment by pierre** [comment]
> The `number_field` doesn't help either: I checked the BCD form and I can actually type anything in there on Safari/Firefox (letters, special characters, ...), Chrome seems to be the only one to enforce valid numbers.

Is it the only one? While the behavior is indeed different, I do see Safari preventing the form from being submitted for instance:

![image](https://cloud.githubusercontent.com/assets/51940/26574709/3941f40e-44d7-11e7-9018-00c426a73358.png)

> What do you think?

I'm actually wondering if we shouldn't just remove the old-style JS validation, and simply rely on HTML5 elements given the above.

**Comment by GregOriol** [comment]
For numbers I think it is ok to use HTML5.

Aren't there more complicated validation in the current forms? some that couldn't be handled with HTML5? (the date string of the BCD form?)

**Comment by pierre** [comment]
> Aren't there more complicated validation in the current forms? some that couldn't be handled with HTML5? (the date string of the BCD form?)

None that we do ourselves (the date validation is handled by by [bootstrap-datepicker](https://github.com/uxsolutions/bootstrap-datepicker) for instance).
