### ISSUE TITLE
Some non responsive sections KAUI

### ISSUE THREAD

**Issue by brickcap** [killbill/killbill-admin-ui#96]
Some sections of the admin page like the menu and the table are non responsive, which makes it a bit hard to navigate the app using the mobile phone. 

As I understand KAUI is already using [twitter-bootstrap](https://github.com/killbill/killbill-admin-ui/blob/master/kaui.gemspec#L37) and the sections in the KAUI demo seem to be using boostrap classes. I'm not sure then why the components appear non responsive? 

For example here is the screenshot of the accounts page using the chrome responsive view. 

![demo killbill io-accounts](https://user-images.githubusercontent.com/2066516/27371221-889cbfcc-567d-11e7-8a13-10fab00a4d18.png)

Can you please let me know what changes should we make to make the screens more responsive? 

Thanks.

**Comment by pierre** [comment]
This is a known issue.

Several attempts have been made to fix it, but it is more tricky than it looks:

* https://github.com/killbill/killbill-admin-ui/pull/59
* https://github.com/killbill/killbill-admin-ui/pull/63

If you would like to contribute, feel free to reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users). Going through the discussion on the mentioned pull requests above will give you the details on some of the challenges.

**Comment by brickcap** [comment]
Thanks @pierre .  I'll post my questions in the mailing list.
